# 数据库连接配置（MySQL 8.0）
# 驱动类名
jdbc.driver=com.mysql.cj.jdbc.Driver
# 数据库连接URL（db_ssm为数据库名）
jdbc.url=jdbc:mysql://127.0.0.1:3306/db_ssm?characterEncoding=utf-8
# 数据库用户名
jdbc.username=ivfzhou
# 数据库密码
jdbc.password=123456
